spring:
  application:
    name: auth-server
  redis:
    password: DKkGa45IbJcrqH3o
    cluster:
      nodes: 10.21.7.16:9000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

server:
  port: 6001

management:
  endpoint:
    health:
      enabled: true
    web:
      exposure:
        indclude: '*'